### PR TITLE
Implemented Modulo Operation and Unit Tests

### LINKED ISSUE #3: Implement Modulo Operator
Extend the calculator for a modulo operator.

### PR DESCRIPTION
**Pull request by PatrickPutz**
closes #3

### CODE REVIEW

**Review by gitc02gh — APPROVED** [review]
Top, Approved

**Review by YanaGum-tech — APPROVED** [review]

**Comment by YanaGum-tech** [comment]
Super gemacht!!!

**Comment by YanaGum-tech** [comment]
Gut gemacht!

**Comment by YanaGum-tech** [comment]
Ok

**Pull request merged**
